2024-05-04 00:10:38,459 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:10:38,646 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:10:38,647 - telegram.ext.Application - INFO - Application started
2024-05-04 00:10:49,097 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:11:24,724 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:11:24,849 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:11:24,850 - telegram.ext.Application - INFO - Application started
2024-05-04 00:11:35,388 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:11:45,505 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:14:04,504 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:14:04,658 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:14:04,659 - telegram.ext.Application - INFO - Application started
2024-05-04 00:14:51,987 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:14:52,112 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:14:52,113 - telegram.ext.Application - INFO - Application started
2024-05-04 00:15:02,580 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:15:12,719 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:15:22,899 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:15:26,688 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:15:26,688 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-05-04 00:15:26,688 - telegram.ext.Application - INFO - Application.stop() complete
2024-05-04 00:15:28,747 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:15:28,862 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:15:28,863 - telegram.ext.Application - INFO - Application started
2024-05-04 00:15:39,300 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:15:49,459 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:15:59,708 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:16:00,662 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:16:00,789 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:16:00,791 - telegram.ext.Application - INFO - Application started
2024-05-04 00:16:01,181 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:01,182 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:01,182 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:05,314 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:05,315 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:05,315 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:06,442 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:06,442 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:06,443 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:11,093 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:11,094 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:11,094 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:12,749 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:12,749 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:12,749 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:17,545 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:16:17,643 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:16:17,676 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:16:17,677 - telegram.ext.Application - INFO - Application started
2024-05-04 00:16:17,767 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:16:17,768 - telegram.ext.Application - INFO - Application started
2024-05-04 00:16:18,089 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:18,090 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:18,090 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:21,226 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:21,227 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:21,227 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:21,606 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:21,607 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:21,607 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:25,379 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:25,379 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:25,379 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:25,778 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:25,780 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:25,780 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:27,422 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:27,424 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:27,424 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:30,874 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:30,875 - telegram.ext.Updater - ERROR - Error while calling `get_updates` one more time to mark all fetched updates as read: %s. Suppressing error to ensure graceful shutdown. When polling for updates is restarted, updates may be fetched again. Please adjust timeouts via `ApplicationBuilder` or the parameter `get_updates_request` of `Bot`.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 439, in _get_updates_cleanup
    await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:30,875 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-05-04 00:16:30,875 - telegram.ext.Application - INFO - Application.stop() complete
2024-05-04 00:16:35,491 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:35,491 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:35,491 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:47,706 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:16:47,706 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:16:47,706 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:03,634 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:17:03,634 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:03,634 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:13,180 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:17:13,304 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:17:13,305 - telegram.ext.Application - INFO - Application started
2024-05-04 00:17:21,166 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:17:21,167 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:21,167 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:25,377 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:17:25,377 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:25,378 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:27,107 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:17:27,528 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:17:28,628 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:17:28,793 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/answerCallbackQuery "HTTP/1.1 200 OK"
2024-05-04 00:17:28,989 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:17:38,817 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:17:48,977 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:17:51,455 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:17:51,455 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:51,456 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:53,227 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:17:55,589 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:17:55,590 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:17:55,590 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:18:03,376 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:18:24,103 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:18:24,237 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:18:24,238 - telegram.ext.Application - INFO - Application started
2024-05-04 00:18:26,040 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:18:26,041 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:18:26,041 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:18:30,223 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:18:30,223 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:18:30,224 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:18:54,909 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:18:55,039 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:18:55,040 - telegram.ext.Application - INFO - Application started
2024-05-04 00:19:01,453 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:19:01,454 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:19:01,454 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:19:05,711 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:19:05,712 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:19:05,712 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:19:43,420 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:19:43,539 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:19:43,539 - telegram.ext.Application - INFO - Application started
2024-05-04 00:19:43,948 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 409 Conflict"
2024-05-04 00:19:43,948 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:19:43,948 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 625, in get_updates
    updates = await super().get_updates(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 4212, in get_updates
    await self._post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 615, in _post
    return await self._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\ext\_extbot.py", line 349, in _do_post
    return await super()._do_post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\_bot.py", line 644, in _do_post
    result = await request.post(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
  File "C:\Users\katsuro\Documents\chat-bot\env\lib\site-packages\telegram\request\_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-05-04 00:21:48,915 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:21:49,033 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:21:49,033 - telegram.ext.Application - INFO - Application started
2024-05-04 00:21:59,470 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:22:09,610 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:22:19,765 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:22:29,935 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:25:58,953 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:25:59,120 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:25:59,121 - telegram.ext.Application - INFO - Application started
2024-05-04 00:26:09,562 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:26:21,174 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:26:38,092 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:26:39,238 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:26:39,239 - telegram.ext.Application - INFO - Application started
2024-05-04 00:26:49,105 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:26:51,287 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:26:54,321 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:26:55,627 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/answerCallbackQuery "HTTP/1.1 200 OK"
2024-05-04 00:27:03,330 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:27:07,746 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:27:09,178 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:27:09,353 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/answerCallbackQuery "HTTP/1.1 200 OK"
2024-05-04 00:27:18,927 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:27:24,665 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:27:24,855 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:27:25,055 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:27:27,747 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:27:27,967 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/answerCallbackQuery "HTTP/1.1 200 OK"
2024-05-04 00:27:28,217 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:27:37,894 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:27:46,571 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:27:58,903 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:27:59,039 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:27:59,040 - telegram.ext.Application - INFO - Application started
2024-05-04 00:28:08,697 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:28:09,278 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:28:10,029 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:28:10,334 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/answerCallbackQuery "HTTP/1.1 200 OK"
2024-05-04 00:28:10,559 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:28:12,411 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:28:22,636 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:28:32,769 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:28:43,008 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:28:53,134 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:29:11,769 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getMe "HTTP/1.1 200 OK"
2024-05-04 00:29:11,886 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/deleteWebhook "HTTP/1.1 200 OK"
2024-05-04 00:29:11,887 - telegram.ext.Application - INFO - Application started
2024-05-04 00:29:14,082 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:29:14,252 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:29:15,183 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:29:15,343 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/answerCallbackQuery "HTTP/1.1 200 OK"
2024-05-04 00:29:15,934 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/sendMessage "HTTP/1.1 200 OK"
2024-05-04 00:29:25,327 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:29:35,470 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
2024-05-04 00:29:45,716 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7021129537:AAHnm5XFjtHrrCbcf_NYThUnVFK0NukeJOM/getUpdates "HTTP/1.1 200 OK"
